"""Add cost tracking columns

Revision ID: d33924b109b2
Revises: ee8e163f1441
Create Date: 2026-03-28 15:44:29.676663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33924b109b2'
down_revision: Union[str, Sequence[str], None] = 'ee8e163f1441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deepgram_duration_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deepgram_cost_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gemini_input_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gemini_output_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gemini_cost_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_column('total_cost_usd')
        batch_op.drop_column('gemini_cost_usd')
        batch_op.drop_column('gemini_output_tokens')
        batch_op.drop_column('gemini_input_tokens')
        batch_op.drop_column('deepgram_cost_usd')
        batch_op.drop_column('deepgram_duration_sec')

    # ### end Alembic commands ###
