"""initial_tables

Revision ID: ee8e163f1441
Revises: 
Create Date: 2026-03-24 16:41:50.219560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8e163f1441'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='audiostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_files_id'), ['id'], unique=False)

    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('model_size', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='transcriptionstatus'), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_id')
    )
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcriptions_id'), ['id'], unique=False)

    op.create_table('transcription_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcription_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcription_segments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcription_segments_id'))

    op.drop_table('transcription_segments')
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcriptions_id'))

    op.drop_table('transcriptions')
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_files_id'))

    op.drop_table('audio_files')
    # ### end Alembic commands ###
